<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>child category</name>
   <tag></tag>
   <elementGuidId>0da8c237-1b6a-4398-8ce7-6ebcb171f023</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/span[1]/span[1]/span[1]/input[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1649154002402</value>
   </webElementProperties>
</WebElementEntity>
