<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>value2</name>
   <tag></tag>
   <elementGuidId>576542a3-c2ab-4d73-9cbc-9ac25b4c6f98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mdc-drawer-app-content.mdc-top-app-bar--fixed-adjust:nth-child(6) main.main-content.main div.container-fluid.shadow-bottom div.row div.col-12.p-1:nth-child(2) div.ibox.float-e-margins div.ibox-content div.table-responsive.col-12.mb-2:nth-child(20) table.table.table-bordered tbody:nth-child(1) tr:nth-child(3) td:nth-child(3) > input.form-control</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1649148955934</value>
   </webElementProperties>
</WebElementEntity>
